<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CustomerDetails.aspx.cs" Inherits="GoodFoodSystem.CustomerDetails" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="row">
        <div class="col-sm-12">
            <asp:GridView ID="GridView1" CssClass="table table-hover" runat="server" DataKeyNames="Customer_ID" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" CellPadding="4" ForeColor="#333333" GridLines="None">
                <AlternatingRowStyle BackColor="White" />
                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
        </div>
    </div>
    
    <div class="col-4 mt-3 p-2 d-flex flex-column">
        <h3>Insert new Dish</h3>
        <div class="form-group">
            <label for="customerName">Customer Name</label>
            <input runat="server" type="text" class="form-control" id="customerName">
        </div>
        <div class="form-group">
            <label for="customerContact">Customer Contact</label>
            <input runat="server" type="tel" class="form-control" id="customerContact">
        </div>
        <div class="form-group">
            <label for="customerEmail">Customer Email</label>
            <input runat="server" type="email" class="form-control" id="customerEmail">
        </div>
        <div class="form-group">
            <label for="customerAddress">Customer Address</label>
            <input runat="server" type="text" class="form-control" id="customerAddress">
        </div>
        <div class="form-group">
            <label for="totalPoints">Total Points</label>
            <input runat="server" type="number" class="form-control" id="totalPoints">
        </div>
        <button runat="server" onserverclick="insertCustomer" class="btn btn-primary">Submit</button>
    </div>
</asp:Content>
