<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="DishDetails.aspx.cs" Inherits="GoodFoodSystem.DishDetails" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="p-2" style="background-color:#f7f7f7">
        <div>
            <h1 class="h2 text-center" style="color:dodgerblue">Dish Details</h1>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <asp:GridView ID="GridView1" CssClass="table  table-hover" runat="server" DataKeyNames="Dish_Code" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" CellPadding="4" ForeColor="#333333" GridLines="None">
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                    <EditRowStyle BackColor="#999999" />
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                    <SortedAscendingHeaderStyle BackColor="#506C8C" />
                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                    <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                </asp:GridView>
            </div>
        </div>
    </div>
    <div class="col-4 mt-3 p-2 d-flex flex-column">
        <h3>Insert new Dish</h3>
        <div class="form-group">
            <label for="dishCode">Dish Code</label>
            <input runat="server" type="text" class="form-control" id="dishCode">
        </div>
        <div class="form-group">
            <label for="dishName">Dish Name</label>
            <input runat="server" type="text" class="form-control" id="dishName">
        </div>
        <div class="form-group">
            <label for="localName">Local Name</label>
            <input runat="server" type="text" class="form-control" id="localName">
        </div>
        <button runat="server" onserverclick="insertDish" class="btn btn-primary">Submit</button>
    </div>
</asp:Content>
